name: go
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5

      - uses: actions/checkout@v4

      - name: go build
        run: go build ./...

      - name: go test
        run: go test -v ./...
